AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Globo DPP backend SAM Template

Parameters:
  Email:
    Type: String
    Description: Email to notify when fail occurs
    Default: youremail@yourprovider.com
  S3Bucket:
    Type: String
    Description: Your Amazon S3 bucket name
    Default: "globo-data-copy"
  DestinationBucket:
    Type: String
    Description: Amazon S3 bucket to bulk frames and audio outputs
    Default: "globo-dev"
  DynamoDBTable:
    Type: String
    Description: DynamoDB Table to store results
    Default: "globo-dpp"

Globals:
  Function:
    Runtime: python3.7
    Handler: app.lambda_handler
    Timeout: 300
    MemorySize: 1024
    Environment:
      Variables:
        INPUT_BUCKET: !Ref S3Bucket
        RESULTS_BUCKET: !Ref DestinationBucket
        DYNAMODB_TABLE_NAME: !Ref DynamoDBTable

Resources:
  #############
  # IAM Roles #
  #############
  MediaConvertS3Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - mediaconvert.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: MediaConvertS3RolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::${S3Bucket}/*"
                  - !Sub "arn:aws:s3:::${DestinationBucket}/*"
  LambdaMediaConvertRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Policies:
        - PolicyName: LambdaMediaConvertRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - mediaconvert:GetJob
                  - mediaconvert:ListJobs
                  - mediaconvert:DescribeEndpoints
                  - mediaconvert:CreateJob
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !GetAtt MediaConvertS3Role.Arn
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::${S3Bucket}/*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:*:*:*:*
              - Effect: Allow
                Action:
                  - dynamodb:Get*
                  - dynamodb:Query
                  - dynamodb:Delete*
                  - dynamodb:PutItem
                Resource: !Sub "arn:aws:dynamodb:*:*:table/${DynamoDBTable}"
  LambdaRekognitionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Policies:
        - PolicyName: LambdaRekognitionPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - rekognition:DetectLabels
                  - rekognition:CompareFaces
                  - rekognition:DetectFaces
                  - rekognition:ListCollections
                  - rekognition:ListFaces
                  - rekognition:SearchFaces
                  - rekognition:SearchFacesByImage
                  - rekognition:DetectText
                  - rekognition:GetCelebrityInfo
                  - rekognition:RecognizeCelebrities
                  - rekognition:DetectModerationLabels
                  - rekognition:GetLabelDetection
                  - rekognition:GetFaceDetection
                  - rekognition:GetContentModeration
                  - rekognition:GetCelebrityRecognition
                  - rekognition:GetFaceSearch
                  - rekognition:GetTextDetection
                  - rekognition:GetSegmentDetection
                  - rekognition:DetectCustomLabels
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::${S3Bucket}/*"
                  - !Sub "arn:aws:s3:::${DestinationBucket}/*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:*:*:*:*
  SimpleLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Policies:
        - PolicyName: LambdaWorkflowRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::${S3Bucket}/*"
                  - !Sub "arn:aws:s3:::${DestinationBucket}/*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:*:*:*:*
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*"
  ####################
  # Lambda Functions #
  ####################
  AudioFrameExtractor:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: video_analysis/audio_frame_extraction/
      Handler: audio-frame-extractor.lambda_handler
      Role: !GetAtt LambdaMediaConvertRole.Arn
      Environment:
        Variables:
          MEDIACONVERT_ROLE: !GetAtt MediaConvertS3Role.Arn
          MEDIACONVERT_DESTINATION_BUCKET: !Ref DestinationBucket
  MediaConvertJobChecker:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: video_analysis/media_convert_job_checker/
      Handler: media-convert-job-checker.lambda_handler
      Role: !GetAtt LambdaMediaConvertRole.Arn
  SceneClassification:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: video_analysis/scene_classification/
      Handler: scene-classification.lambda_handler
      Role: !GetAtt LambdaRekognitionRole.Arn

  ####################
  #    SNS Topics    #
  ####################
  MediaConvertTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint:
            !GetAtt MediaConvertJobChecker.Arn
          Protocol: "lambda"
      TopicName: "MediaConvertJobStatus"
  ################
  # IAM Policies #
  ################
  EventTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sns:Publish
            Resource: "*"
      Topics:
        - !Ref MediaConvertTopic
  ####################
  #    CloudWatch    #
  ####################
  MediaConvertJobEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - "aws.mediaconvert"
        detail-type:
          - "MediaConvert Job State Change"
        detail:
          status:
            - "COMPLETE"
            - "ERROR"
      Targets:
        -
          Arn: !Ref MediaConvertTopic
          Id: "MCJobsTopic"
          InputTransformer:
            InputPathsMap:
              job_id: "$.detail.jobId"
              status: "$.detail.status"
            InputTemplate: |
              "{'job_id': '<job_id>','status':'<status>'}"
  ####################
  #  DynamoDB Table  #
  ####################
  VideoAnalysisTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      TableName: !Ref DynamoDBTable