AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Globo DPP backend SAM Template

Parameters:
  Email:
    Type: String
    Description: Email to notify when fail occurs
    Default: youremail@yourprovider.com
  S3Bucket:
    Type: String
    Description: Your Amazon S3 bucket name
    Default: "globo-data-copy"
  DestinationBucket:
    Type: String
    Description: Amazon S3 bucket to bulk frames and audio outputs
    Default: "globo-dev"
  DynamoDBTable:
    Type: String
    Default: "globo-jobs"

Globals:
  Function:
    Runtime: python3.7
    Handler: app.lambda_handler
    Timeout: 300
    MemorySize: 1024
    Layers:
      - !Ref Shared

Resources:
  #############
  # IAM Roles #
  #############
  MediaConvertS3Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - mediaconvert.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: MediaConvertS3RolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::${S3Bucket}/*"
                  - !Sub "arn:aws:s3:::${DestinationBucket}/*"
        - PolicyName: MediaConvertCloudWatchEventsPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:*
                  - sns:*
                  - logs:*
                Resource:
                  - "*"
  LambdaMediaConvertRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Policies:
        - PolicyName: LambdaMediaConvertRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - mediaconvert:GetJob
                  - mediaconvert:ListJobs
                  - mediaconvert:DescribeEndpoints
                  - mediaconvert:CreateJob
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !GetAtt MediaConvertS3Role.Arn
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::${S3Bucket}/*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:*:*:*:*
              - Effect: Allow
                Action:
                  - dynamodb:Get*
                  - dynamodb:Delete*
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:BatchWriteItem
                Resource:
                  - !Sub "arn:aws:dynamodb:*:*:table/${DynamoDBTable}"
                  - !Sub "arn:aws:dynamodb:*:*:table/${DynamoDBTable}/*"
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource:
                  - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:*"
  LambdaRekognitionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Policies:
        - PolicyName: LambdaRekognitionPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - rekognition:DetectLabels
                  - rekognition:CompareFaces
                  - rekognition:DetectFaces
                  - rekognition:ListCollections
                  - rekognition:ListFaces
                  - rekognition:SearchFaces
                  - rekognition:SearchFacesByImage
                  - rekognition:StartTextDetection
                  - rekognition:GetTextDetection
                  - rekognition:DetectText
                  - rekognition:GetCelebrityInfo
                  - rekognition:RecognizeCelebrities
                  - rekognition:DetectModerationLabels
                  - rekognition:GetLabelDetection
                  - rekognition:GetFaceDetection
                  - rekognition:GetContentModeration
                  - rekognition:GetCelebrityRecognition
                  - rekognition:GetFaceSearch
                  - rekognition:GetTextDetection
                  - rekognition:GetSegmentDetection
                  - rekognition:DetectCustomLabels
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::${S3Bucket}/*"
                  - !Sub "arn:aws:s3:::${DestinationBucket}/*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:*:*:*:*
              - Effect: Allow
                Action:
                  - dynamodb:Get*
                  - dynamodb:Delete*
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:PutItem
                  - dynamodb:BatchWriteItem
                Resource:
                  - !Sub "arn:aws:dynamodb:*:*:table/${DynamoDBTable}"
                  - !Sub "arn:aws:dynamodb:*:*:table/${DynamoDBTable}/*"
  APILambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Policies:
        - PolicyName: LambdaWorkflowRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub "arn:aws:s3:::${S3Bucket}/*"
                  - !Sub "arn:aws:s3:::${DestinationBucket}/*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:*:*:*:*
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*"
              - Effect: Allow
                Action:
                  - dynamodb:Get*
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !Sub "arn:aws:dynamodb:*:*:table/${DynamoDBTable}"
                  - !Sub "arn:aws:dynamodb:*:*:table/${DynamoDBTable}/*"
  ####################
  #        API       #
  ####################
  RestAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: RestAPI
      StageName: Prod
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: !Sub "${AWS::StackName}-usage-plan"
          Description: Customer usage plan
          Quota:
            Limit: 5000
            Period: MONTH
          Throttle:
            BurstLimit: 200
            RateLimit: 100
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'GET,POST'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
  ####################
  # Lambda Functions #
  ####################
  StartAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/start_analysis/
      Handler: main.lambda_handler
      Role: !GetAtt LambdaMediaConvertRole.Arn
      Environment:
        Variables:
          DDB_TABLE: !Ref ResultsTable
          MEDIA_CONVERT_ARN: !GetAtt MediaConvertS3Role.Arn
          DEST_S3_BUCKET: !Ref DestinationBucket
          IN_S3_BUCKET: !Ref S3Bucket
          SNS_TOPIC: !Ref VideoAnalysisTopic
      Events:
        StartVideoAnalysis:
          Type: Api
          Properties:
            Path: /analysis/start
            Method: POST
            RestApiId: !Ref RestAPI
            Auth:
              ApiKeyRequired: true
  MediaConvertJobChecker:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: video_analysis/media_convert_job_checker/
      Handler: media-convert-job-checker.lambda_handler
      Role: !GetAtt LambdaMediaConvertRole.Arn
      Environment:
        Variables:
          SNS_TOPIC: !Ref VideoAnalysisTopic
          MC_JOB_INDEX_NAME: "MediaConvertJobIndex"
          IN_S3_BUCKET: !Ref S3Bucket
          DDB_TABLE: !Ref ResultsTable
  GetAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/get_analysis/
      Handler: main.lambda_handler
      Role: !GetAtt APILambdaRole.Arn
      Environment:
        Variables:
          DDB_TABLE: !Ref ResultsTable
      Events:
        GetVideoAnalysis:
          Type: Api
          Properties:
            Path: /analysis/{s3key}
            Method: GET
            RestApiId: !Ref RestAPI
            Auth:
              ApiKeyRequired: true
  ######################
  # Analysis Functions #
  ######################
  SceneClassification:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: analysis/object_scene_classification/
      Handler: osc.lambda_handler
      Role: !GetAtt LambdaRekognitionRole.Arn
      Timeout: 900
      Environment:
        Variables:
          IN_S3_BUCKET: !Ref S3Bucket
          DDB_TABLE: !Ref ResultsTable
          DEST_S3_BUCKET: !Ref DestinationBucket
  BrandFromTextAnalysis:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: analysis/brand_from_text/
      Handler: bft.lambda_handler
      Role: !GetAtt LambdaRekognitionRole.Arn
      Environment:
        Variables:
          DDB_TABLE: !Ref ResultsTable
          IN_S3_BUCKET: !Ref S3Bucket
          DEST_S3_BUCKET: !Ref DestinationBucket
          SIM_THRESHOLD: 0.7
#      Policies:
#        - Version: "2012-10-17"
#          Statement:
#            - Effect: Allow
#              Action:
#                - rekognition:*
#              Resource: "*"
#            - Effect: Allow
#              Action:
#                - dynamodb:*
#              Resource: "*"
#            - Effect: Allow
#              Action:
#                - sns:Publish
#              Resource: "*"
#            - Effect: Allow
#              Action:
#                - s3:*
#              Resource: "*"
  ####################
  #Lambda Permissions#
  ####################
  MCLambdaInvokePermissions:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      Principal: "sns.amazonaws.com"
      SourceArn: !Ref MediaConvertTopic
      FunctionName: !GetAtt MediaConvertJobChecker.Arn
  SceneClassificationLambdaInvokePermissions:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      Principal: "sns.amazonaws.com"
      SourceArn: !Ref VideoAnalysisTopic
      FunctionName: !GetAtt SceneClassification.Arn
  BrandFromTextLambdaInvokePermissions:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      Principal: "sns.amazonaws.com"
      SourceArn: !Ref VideoAnalysisTopic
      FunctionName: !GetAtt BrandFromTextAnalysis.Arn
  #####################
  #Lambda Custom Layer#
  #####################
  Shared:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: "AnalysisSaver"
      Description: "Library to save results from analysis to DynamoDB and ElastiSearch"
      ContentUri: shared/
      CompatibleRuntimes:
        - python3.7
      RetentionPolicy: Delete
  ####################
  #    SNS Topics    #
  ####################
  MediaConvertTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint:
            !GetAtt MediaConvertJobChecker.Arn
          Protocol: "lambda"
      TopicName: "MCJobStatus"
  VideoAnalysisTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint:
            !GetAtt SceneClassification.Arn
          Protocol: "lambda"
      TopicName: "VidAnalysisTopic"
  bftSub:
    Type: AWS::SNS::Subscription
    Properties: 
      Endpoint: !GetAtt BrandFromTextAnalysis.Arn
      Protocol: lambda
      FilterPolicy: '{"analysis": ["all", "bft"]}'
      TopicArn: !Ref VideoAnalysisTopic
  EmailTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: NotificationTopic
      Subscription:
        - Endpoint: !Ref Email
          Protocol: email

  ################
  # IAM Policies #
  ################
  EventTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sns:Publish
            Resource: "*"
      Topics:
        - !Ref MediaConvertTopic
  ####################
  #    CloudWatch    #
  ####################
  MediaConvertJobEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - "aws.mediaconvert"
        detail-type:
          - "MediaConvert Job State Change"
        detail:
          status:
            - "COMPLETE"
            - "ERROR"
      Targets:
        -
          Arn: !Ref MediaConvertTopic
          Id: "MCJobsTopic"
          InputTransformer:
            InputPathsMap:
              job_id: "$.detail.jobId"
            InputTemplate: |
              "job_id:<job_id>"
  #####################
  #  DynamoDB Table   #
  #####################
  ResultsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDBTable
      AttributeDefinitions:
        - AttributeName: S3Key
          AttributeType: S
        - AttributeName: AttrType
          AttributeType: S
        - AttributeName: JobId
          AttributeType: S
      KeySchema:
        - AttributeName: S3Key
          KeyType: HASH
        - AttributeName: AttrType
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: JobIdIndex
          KeySchema:
            - AttributeName: S3Key
              KeyType: HASH
            - AttributeName: JobId
              KeyType: RANGE
          Projection:
            NonKeyAttributes:
              - analysis
            ProjectionType: INCLUDE
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: cost
          Value: aws-ee
#####################
#       OUTPUTS     #
#####################
Outputs:
  RestAPIUrl:
    Value: !Sub "https://${RestAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod"